language: rust
sudo: false
script:
  - 'if [ "$WITH_LOCK" != "true" ]; then rm -f Cargo.lock; fi'
  - "cargo test --no-default-features && \
     cargo test && \
     cargo test --all-features"
cache:
  directories:
    - target/debug/deps
    - target/debug/build
    - target/debug/incremental

rust: 1.26.2
env: # important!
matrix:
  include:
    - rust: 1.26.2
      os: osx
      env: WITH_LOCK=true
    - rust: stable
      os: osx
    - rust: 1.26.2
      env: WITH_LOCK=true
    - rust: stable
    - rust: nightly
      env: WITH_LOCK=true
    - rust: beta
      env: MAY_FAIL=true
    - rust: nightly
      env: MAY_FAIL=true
  allow_failures:
    - env: MAY_FAIL=true
