language: rust
sudo: false
script:
  - 'if [ "$WITH_LOCK" != "true" ]; then cargo update; fi'
  - 'cargo test --no-default-features'
  - 'cargo test --no-default-features --features client'
  - 'if [ "$MAY_FAIL" != "true" ]; then cargo test; fi'
  - 'if [ "$MAY_FAIL" == "true" ]; then cargo test --all-features; fi'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

rust: 1.26.2
env: # important!
matrix:
  include:
    - rust: 1.26.2
      os: osx
      env: WITH_LOCK=true
    - rust: stable
      os: osx
    - rust: 1.26.2
      env: WITH_LOCK=true
    - rust: 1.27.2
      env: WITH_LOCK=true
    - rust: stable
    - rust: nightly
      env: WITH_LOCK=true
    - rust: beta
      env: MAY_FAIL=true
    - rust: nightly
      env: MAY_FAIL=true
  allow_failures:
    - env: MAY_FAIL=true
