language: rust
sudo: false
script:
  - 'cargo test --no-default-features'
  - 'cargo test --no-default-features --features futio'
  - 'cargo build --all-features --bins --examples'
  - 'if [ "$MAY_FAIL" != "true" ]; then cargo test; fi'
  - 'if [ "$MAY_FAIL" == "true" ]; then cargo test --all-features; fi'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

rust: 1.31.0
env: # important!
matrix:
  include:
    - rust: 1.31.0
      os: osx
    - rust: nightly
