language: rust
dist: xenial
script:
  - 'cargo test --no-default-features'
  - 'cargo test --no-default-features --features futio'
  - 'cargo build --all-features --bins --examples'
  - 'cargo test'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

env: # important!
matrix:
  include:
    - rust: 1.31.0
    - rust: nightly
    - rust: 1.31.0
      os: osx
