language: rust
dist: xenial
script:
  - 'if [ "$WITH_LOCK" != "true" ]; then cargo update; fi'
  - 'cargo test --no-default-features'
  - 'cargo test --no-default-features --features futio'
  - 'cargo build --all-features --bins --examples'
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --all-features --all-targets; fi'
  - 'if [ "$MAY_FAIL" != "true" ]; then cargo test; fi'
  - 'if [ "$MAY_FAIL" == "true" ]; then cargo test --all-features; fi'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

rust: 1.31.0
env: # important!
matrix:
  include:
    - rust: 1.31.0
      os: osx
      env: WITH_LOCK=true
    - rust: 1.31.0
      env: WITH_LOCK=true
    - rust: nightly
      env: WITH_LOCK=true
    - rust: nightly
      env: MAY_FAIL=true
  allow_failures:
    - env: MAY_FAIL=true
