os: Visual Studio 2015

environment:
  matrix:
    - channel: 1.39.0
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - 'cargo test  --manifest-path body-image/Cargo.toml --no-default-features'
  - 'cargo test  --manifest-path body-image/Cargo.toml --all-features'
  - 'cargo test  --manifest-path barc/Cargo.toml --no-default-features'
  - 'cargo test  --manifest-path barc/Cargo.toml --no-default-features --features mmap'
  - 'cargo test  --manifest-path barc/Cargo.toml --no-default-features --features brotli'
  - 'cargo test  --manifest-path barc/Cargo.toml --all-features'
  - 'cargo test  --manifest-path body-image-futio/Cargo.toml --no-default-features'
  - 'cargo test  --manifest-path body-image-futio/Cargo.toml --no-default-features --features mmap'
  - 'cargo test  --manifest-path body-image-futio/Cargo.toml --no-default-features --features brotli'
  - 'cargo test  --manifest-path body-image-futio/Cargo.toml'
  - 'cargo build --manifest-path barc-cli/Cargo.toml --no-default-features'
  - 'cargo build --manifest-path barc-cli/Cargo.toml --no-default-features --features mmap'
  - 'cargo build --manifest-path barc-cli/Cargo.toml --no-default-features --features brotli'
  - 'cargo build --manifest-path barc-cli/Cargo.toml --no-default-features --features futio'
  - 'cargo build --manifest-path barc-cli/Cargo.toml --all-features'
