[package]
name          = "body-image-futio"
version       = "1.1.0"
edition       = "2018"
authors       = ["David Kellum <dek-oss@gravitext.com>"]
license       = "MIT/Apache-2.0"
description   = "Futures based asynchronous I/O for body-image."
documentation = "https://docs.rs/body-image"
repository    = "https://github.com/dekellum/body-image"
readme        = "README.md"
keywords      = ["futures", "async", "http", "hyper"]
categories    = ["web-programming::http-client", "web-programming::http-server"]

[badges]
travis-ci = { repository="dekellum/body-image" }

[dependencies]
body-image = { version=">=1.1.0, <2", default-features=false }
brotli     = { version=">=2.2.1, <4", optional=true }
bytes      = { version=">=0.4.6, <2" }
flate2     = { version=">=1.0.1, <2" }
futures    = { version=">=0.1.20, <0.2" }
http       = { version=">=0.1.6, <2" }
httparse   = { version=">=1.2.4, <2" }
hyper      = { version=">=0.12.1, <2" }
hyper-tls  = { version=">=0.3.0, <2" }
hyperx     = { version=">=0.14.0, <2" }
tao-log    = { version=">=0.1.0, <2" }
memmap     = { version=">=0.7.0, <2", optional=true }
olio       = { version=">=1.0.0, <2", default-features=false }
tokio      = { version=">=0.1.14, <0.2", default-features=false, features=["rt-full"] }
tokio-threadpool = { version=">=0.1.10, <0.2" }

[features]
default = ["mmap", "brotli"]
mmap = ["memmap", "olio/mmap", "body-image/mmap"]

may_fail = [] # Tests which may fail

[lib]
doctest = false
bench = false

[dev-dependencies]
fern        = { version=">=0.5.5, <2" }
rand        = { version=">=0.6.1, <2" }
tokio-tcp   = { version=">=0.1.3, <0.2" }
