[package]
name          = "barc"
version       = "0.6.0"
edition       = "2018"
authors       = ["David Kellum <dek-oss@gravitext.com>"]
license       = "MIT/Apache-2.0"
description   = "Basic Archive (BARC) file reader and writer, for HTTP dialogs"
documentation = "https://docs.rs/body-image"
repository    = "https://github.com/dekellum/body-image"
readme        = "README.md"
keywords      = ["http", "compression", "serialization"]
categories    = ["web-programming"]

exclude       = ["barc.stash/*"]

[badges]
travis-ci = { repository = "dekellum/body-image" }

[dependencies]
body-image = { version = ">=0.6.0, <2", default-features = false }
brotli     = { version = ">=2.2.1, <3", optional = true }
bytes      = { version = ">=0.4.6, <2" }
failure    = { version = ">=0.1.2, <2", default-features = false, features = ["std"] }
flate2     = { version = ">=1.0.1, <2" }
http       = { version = ">=0.1.6, <2" }
httparse   = { version = ">=1.2.4, <2" }
log        = { version = ">=0.4.0, <2" }
memmap     = { version = ">=0.6.2, <2", optional = true }
olio       = { version = ">=0.4.0, <2", default-features = false }
tempfile   = { version = ">=2.2.0, <4" }

[features]
default = ["mmap", "brotli"]
mmap = ["memmap", "olio/mmap", "body-image/mmap"]

[lib]
doctest = false
bench = false

[package.metadata.docs.rs]
features = ["mmap", "brotli"]
