name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '57 15 * * 1,4'

env:
  RUSTFLAGS: -Dwarnings

jobs:

  test:
    name: ${{ matrix.rust }} ${{ matrix.os }} ${{ join(matrix.extras) }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - rust: 1.45.2
            os: ubuntu-20.04
          - rust: 1.45.2
            os: macos-latest
          - rust: 1.45.2
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Test futio (post_echo_body)
        working-directory: body-image-futio
        run: cargo test post_echo_body -- --test-threads=1 --nocapture
        env:
          RUST_BACKTRACE: 1
          TEST_LOG: 2

      - name: Test futio (post_echo_async_body)
        working-directory: body-image-futio
        run: cargo test post_echo_async_body -- --test-threads=1 --nocapture
        env:
          RUST_BACKTRACE: 1
          TEST_LOG: 2

      - name: Test futio (tests::server)
        working-directory: body-image-futio
        run: cargo test tests::server -- --test-threads=1 --nocapture
        env:
          RUST_BACKTRACE: 1
          TEST_LOG: 2

